"""Generate exact topic grants from the explicit synthetic registry; no broker."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
REGISTRY = ROOT / "ops/compose/device-registry.json"
OUTPUT = ROOT / "ops/compose/mosquitto.acl"
CHANNELS = ("telemetry", "event", "health", "command", "ack")
LEGACY = {"chirpstack": ["write application/+/device/+/event/+", "read eu868/gateway/+/event/+"],
          "aquilon": ["read application/+/device/+/event/up"]}


def identifier(value):
    if type(value) is not str or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", value):
        raise ValueError("unsafe topic identity")
    return value


def topic(site, zone, device, channel):
    if channel not in CHANNELS:
        raise ValueError("unknown topic channel")
    return "/".join(("poseidon", "v1", identifier(site), identifier(zone), identifier(device), channel))


def generate(registry):
    if (type(registry) is not dict or set(registry) != {"schema_version", "simulation", "devices", "principals", "legacy_service_grants"}
            or registry["schema_version"] != "poseidon.topic-registry.v1" or registry["simulation"] is not True
            or registry["legacy_service_grants"] != LEGACY):
        raise ValueError("unknown or invalid topic registry")
    devices = {}
    for row in registry["devices"]:
        if type(row) is not dict or set(row) != {"device_id", "site_id", "zone_id", "revoked", "health_profile"} or type(row["revoked"]) is not bool:
            raise ValueError("invalid device registry row")
        device_id = identifier(row["device_id"])
        identifier(row["site_id"])
        if device_id in devices:
            raise ValueError("duplicate device identity")
        if row["zone_id"] is not None:
            identifier(row["zone_id"])
        profile = row["health_profile"]
        if profile is not None and (type(profile) is not dict or set(profile) != {"stale_after_s", "offline_after_s"} or any(type(v) is not int for v in profile.values()) or not 0 < profile["stale_after_s"] < profile["offline_after_s"] <= 86400):
            raise ValueError("invalid health profile")
        devices[device_id] = row
    grants = {user: list(values) for user, values in LEGACY.items()}
    seen = set(grants)
    for principal in registry["principals"]:
        if type(principal) is not dict or set(principal) != {"username", "role", "site_ids", "device_id", "revoked"} or type(principal["revoked"]) is not bool:
            raise ValueError("invalid principal registry row")
        user = identifier(principal["username"])
        if user in seen:
            raise ValueError("duplicate principal username")
        seen.add(user)
        if principal["role"] not in {"viewer", "reviewer", "admin", "operator", "device"} or type(principal["site_ids"]) is not list or not principal["site_ids"]:
            raise ValueError("invalid principal role/scope")
        for site in principal["site_ids"]:
            identifier(site)
        if len(set(principal["site_ids"])) != len(principal["site_ids"]):
            raise ValueError("duplicate site scope")
        if principal["role"] == "device":
            identifier(principal["device_id"])
            bound = devices.get(principal["device_id"])
            if bound is None or principal["site_ids"] != [bound["site_id"]]:
                raise ValueError("device principal scope mismatch")
        elif principal["device_id"] is not None:
            raise ValueError("human principal cannot bind a device")
        if principal["revoked"]:
            continue
        permissions = []
        for device in sorted(devices.values(), key=lambda item: item["device_id"]):
            if device["revoked"] or device["zone_id"] is None or device["health_profile"] is None or device["site_id"] not in principal["site_ids"]:
                continue
            if principal["role"] == "device" and principal["device_id"] != device["device_id"]:
                continue
            for channel in CHANNELS:
                if principal["role"] == "device":
                    access = "read" if channel == "command" else "write"
                elif channel == "command":
                    if principal["role"] != "operator":
                        continue
                    access = "write"
                else:
                    access = "read"
                permissions.append(access + " " + topic(device["site_id"], device["zone_id"], device["device_id"], channel))
        if permissions:
            grants[user] = permissions
    lines = ["# Generated by scripts/platform/generate_topic_acl.py; do not edit.",
             "# Synthetic registry only. No broker/device dispatch is launched by this tranche.",
             "# command/ack retain=false is a publisher/subscriber rule, not an ACL capability."]
    for user in sorted(grants):
        lines += ["", "user " + user, *[" topic " + grant for grant in grants[user]]]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate(json.loads(REGISTRY.read_text()))
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit("generated ACL differs; regenerate explicitly")
    else:
        OUTPUT.write_text(generated)


if __name__ == "__main__":
    main()
