"""Synthetic secrets exist only in bounded temporary fixture directories."""
from __future__ import annotations

from contextlib import redirect_stdout, redirect_stderr
import copy
import importlib.util
import io
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location("poseidon_secrets_scan", ROOT / "scripts/assurance/secrets_scan.py")
scanner = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(scanner)


def seeds():
    # Deliberate invalid/non-issued fixtures, constructed so this test's source
    # itself does not contain credential-shaped literals requiring exemptions.
    return {
        "private-key-pem": "-----BEGIN " + "PRIVATE KEY-----",
        "aws-access-key": "AKIA" + "SYNTHETIC" + "0" * 7,
        "github-token": "ghp_" + "Synthetic" * 4,
        "slack-token": "xoxb-" + "synthetic-" * 4,
        "google-api-key": "AIza" + "Synthetic" * 3 + "0" * 8,
        "stripe-live-key": "sk_" + "live_" + "Synthetic" * 3,
        "credential-assignment": 'api_key = "' + "SYNTHETIC_UNUSABLE_FIXTURE_0000" + '"',
        "credential-url": "postgres://synthetic:" + "SYNTHETIC_UNUSABLE_0000" + "@localhost/db",
    }


class ScannerTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="poseidon-secrets-synthetic-")
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.allowlist = self.root / "allowlist.json"
        self.write_allowlist([])

    def write_allowlist(self, entries):
        self.allowlist.write_text(json.dumps({"version": 1, "entries": entries}))

    def entry(self, match):
        return {k: match[k] for k in ("path", "pattern", "fingerprint")} | {"occurrences": 1, "category": "synthetic-fixture", "justification": "Synthetic unusable fixture generated by this test, never a real issued credential."}

    def test_every_fixed_pattern_detects_seed_and_redacts(self):
        self.assertEqual(set(seeds()), set(scanner.PATTERNS))
        for pattern, secret in seeds().items():
            with self.subTest(pattern=pattern):
                matches = scanner.matches_in_text("tests/fixture.txt", "plain\n" + secret + "\n")
                self.assertEqual([m["pattern"] for m in matches], [pattern])
                self.assertEqual(matches[0]["line"], 2)
                self.assertEqual(set(matches[0]), {"path", "line", "pattern", "fingerprint"})
                self.assertNotIn(secret, json.dumps(matches))

    def test_new_untracked_source_is_rejected(self):
        (self.root / "new-config.env").write_text(seeds()["github-token"])
        report = scanner.scan(self.root, [])
        self.assertFalse(report["ok"])
        self.assertEqual(report["counts"]["unallowlisted"], 1)
        self.assertTrue(report["coverage"]["includes_untracked"])

    def test_narrow_allowlist_and_novel_secret(self):
        (self.root / "tests").mkdir()
        path = self.root / "tests/fixture.txt"
        seed = seeds()["github-token"]
        path.write_text(seed)
        match = scanner.matches_in_text("tests/fixture.txt", seed)[0]
        self.write_allowlist([self.entry(match)])
        entries = scanner.load_allowlist(self.allowlist)
        self.assertTrue(scanner.scan(self.root, entries)["ok"])
        path.write_text(seed + "\n" + seeds()["aws-access-key"])
        report = scanner.scan(self.root, entries)
        self.assertFalse(report["ok"])
        self.assertEqual(report["counts"]["unallowlisted"], 1)

    def test_allowlist_does_not_follow_identical_value_to_other_path(self):
        (self.root / "tests").mkdir()
        seed = seeds()["github-token"]
        (self.root / "tests/first.txt").write_text(seed)
        (self.root / "tests/second.txt").write_text(seed)
        entry = self.entry(scanner.matches_in_text("tests/first.txt", seed)[0])
        self.assertEqual(scanner.scan(self.root, [entry])["counts"]["unallowlisted"], 1)

    def test_stale_allowlist_and_extra_occurrence_fail(self):
        seed = seeds()["aws-access-key"]
        entry = self.entry(scanner.matches_in_text("tests/fixture.txt", seed)[0])
        self.assertEqual(scanner.scan(self.root, [entry])["counts"]["allowlist_errors"], 1)
        (self.root / "tests").mkdir()
        (self.root / "tests/fixture.txt").write_text(seed + "\n" + seed)
        self.assertEqual(scanner.scan(self.root, [entry])["counts"]["allowlist_errors"], 1)

    def test_reject_overbroad_malformed_and_duplicate_entries(self):
        entry = self.entry(scanner.matches_in_text("tests/fixture.txt", seeds()["aws-access-key"])[0])
        changes = [
            {"path": "tests/*"}, {"path": "../outside"}, {"path": "/tmp/file"}, {"path": "tests/./fixture.txt"},
            {"path": "tests//fixture.txt"}, {"path": "src/production.py"}, {"path": "tests/.local/file.txt"},
            {"pattern": "*"}, {"fingerprint": "*"}, {"justification": "approved"}, {"occurrences": 0},
            {"occurrences": True}, {"regex": ".*"},
        ]
        for change in changes:
            with self.subTest(change=change):
                self.write_allowlist([entry | change])
                with self.assertRaises(ValueError):
                    scanner.load_allowlist(self.allowlist)
        self.write_allowlist([entry, copy.deepcopy(entry)])
        with self.assertRaises(ValueError):
            scanner.load_allowlist(self.allowlist)

    def test_excludes_private_runtime_git_dependencies_and_symlinks(self):
        for directory in (".git", ".local", ".venv", "node_modules"):
            (self.root / directory).mkdir()
            (self.root / directory / "not-read.txt").write_text(seeds()["github-token"])
        (self.root / "outside-link").symlink_to(self.root / ".local", target_is_directory=True)
        (self.root / "secret-link.txt").symlink_to(self.root / ".local/not-read.txt")
        report = scanner.scan(self.root, [])
        self.assertTrue(report["ok"])
        self.assertEqual(report["coverage"]["skipped"]["excluded-directory"], 4)
        self.assertEqual(report["coverage"]["skipped"]["symlink"], 2)

    def test_binary_logs_and_oversized_text_coverage(self):
        (self.root / "fixture.pgm").write_bytes(b"\xff\xfe")
        (self.root / "generated.log").write_text(seeds()["github-token"])
        (self.root / "blob.dat").write_bytes(b"\x00" + seeds()["github-token"].encode())
        report = scanner.scan(self.root, [])
        self.assertTrue(report["ok"])
        self.assertEqual(report["coverage"]["skipped"], {"binary-extension": 1, "binary-nul": 1, "generated-log-output": 1})
        (self.root / "source.txt").write_text("z" * 101)
        with patch.object(scanner, "MAX_FILE_BYTES", 100):
            report = scanner.scan(self.root, [])
        self.assertFalse(report["ok"])
        self.assertIn({"path": "source.txt", "reason": "file-byte-limit"}, report["coverage_errors"])

    def test_unknown_encoding_and_special_file_fail_closed(self):
        (self.root / "source.txt").write_bytes(b"\xff\xfe")
        report = scanner.scan(self.root, [])
        self.assertEqual(report["counts"]["coverage_errors"], 1)
        self.assertFalse(report["ok"])

    def test_total_and_count_bounds(self):
        (self.root / "a.txt").write_text("plain")
        (self.root / "b.txt").write_text("plain")
        with patch.object(scanner, "MAX_FILES", 1):
            self.assertFalse(scanner.scan(self.root, [])["ok"])
        with patch.object(scanner, "MAX_TOTAL_BYTES", 1):
            self.assertFalse(scanner.scan(self.root, [])["ok"])

    def test_home_root_refused(self):
        for root in (Path.home(), Path("/")):
            with self.assertRaises(ValueError):
                scanner.scan(root, [])

    def test_cli_exit_codes_and_redaction(self):
        out, err = io.StringIO(), io.StringIO()
        secret = seeds()["github-token"]
        (self.root / "new.txt").write_text(secret)
        with redirect_stdout(out), redirect_stderr(err):
            code = scanner.main(["--root", str(self.root), "--allowlist", str(self.allowlist)])
        self.assertEqual(code, 1)
        self.assertNotIn(secret, out.getvalue() + err.getvalue())
        self.allowlist.write_text("invalid JSON " + secret)
        with redirect_stdout(out), redirect_stderr(err):
            code = scanner.main(["--root", str(self.root), "--allowlist", str(self.allowlist)])
        self.assertEqual(code, 2)
        self.assertNotIn(secret, out.getvalue() + err.getvalue())

    def test_pem_fingerprint_binds_body_not_just_header(self):
        header = seeds()["private-key-pem"]
        first = scanner.matches_in_text("tests/key.txt", header + "\nSYNTHETIC_BODY_ONE\n")[0]
        second = scanner.matches_in_text("tests/key.txt", header + "\nSYNTHETIC_BODY_TWO\n")[0]
        self.assertNotEqual(first["fingerprint"], second["fingerprint"])

    def test_non_synthetic_allowlist_categories_are_rejected(self):
        base = {"path": "tests/fixtures/example.txt", "pattern": "credential-assignment", "fingerprint": "0" * 64, "occurrences": 1, "justification": "Synthetic unusable fixture generated by this test, never a real issued credential.", "category": "synthetic-fixture"}
        self.write_allowlist([base])
        scanner.load_allowlist(self.allowlist)
        for change in ({"category": "retained-third-party-evidence"}, {"category": "vendor"}, {"source_sha256": "0" * 64}, {"approval_reference": "root"}):
            with self.subTest(change=change):
                self.write_allowlist([base | change])
                with self.assertRaises(ValueError):
                    scanner.load_allowlist(self.allowlist)

    def test_actual_project_source_has_no_unallowlisted_matches(self):
        report = scanner.scan(ROOT, scanner.load_allowlist(ROOT / scanner.ALLOWLIST))
        self.assertTrue(report["ok"], json.dumps({k: report[k] for k in ("counts", "unallowlisted", "allowlist_errors", "coverage_errors")}, sort_keys=True))
        self.assertEqual(report["allowlisted_categories"], {"synthetic-fixture": 3})
        self.assertFalse(report["publication_blocked"])
        self.assertEqual(report["retained_vendor_exceptions"], [])
        self.assertEqual(report["open_items"], [])


if __name__ == "__main__":
    unittest.main()
