"""Source-only parser/checker regressions with explicitly synthetic evidence.

All ELF/bin/sdkconfig files, compiler logs and vendor outputs below are invented
fixtures, not native builds, target execution, persistence or field evidence.
Only bounded Python fixture processes run in the subprocess tests; no toolchain,
compiler, device, network, radio or sensor is used.
"""
from __future__ import annotations

from contextlib import redirect_stdout
import hashlib
import io
import json
import os
from pathlib import Path
import signal
import struct
import subprocess
import sys
import tempfile
import time
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts/assurance"))
import check_monitor_build as checker


def synthetic_elf() -> bytes:
    data = bytearray(256)
    data[:16] = b"\x7fELF\x01\x01\x01" + bytes(9)
    struct.pack_into("<HHIIIIIHHHHHH", data, 16, 2, 94, 1, 0x40081200, 52, 84, 0x300, 52, 32, 1, 40, 2, 1)
    data[200:] = b"SYNTHETIC ELF FIXTURE".ljust(56, b"!")
    return bytes(data)


def synthetic_nm() -> str:
    # Addresses are invented and carry no initializer/layout meaning.
    records = [f"{0x400D1000 + i * 16:08x} {'t' if 'worker_entry' in name else 'T'} {name}" for i, name in enumerate(checker.REQUIRED_TEXT_SYMBOLS)]
    return "\n".join(records + ["         U unrelated_synthetic_undefined", "3ffb0000 b synthetic_data"]) + "\n"


def synthetic_objdump(elf: Path) -> str:
    return f"\n{elf}:     file format elf32-xtensa-le\narchitecture: xtensa, flags 0x00000112:\nEXEC_P, HAS_SYMS, D_PAGED\nstart address 0x40081200\n\n"


def synthetic_disassembly(elf: Path, symbol: str) -> str:
    # Invented minimal body, intentionally identical for both profiles. Neither
    # these instructions nor their addresses establish monitor enabled state.
    return f"\n{elf}:     file format elf32-xtensa-le\n\nDisassembly of section .flash.text:\n\n400d1000 <{symbol}>:\n400d1000:\t004136\tentry\ta1, 32\n400d1003:\tf01d\tretw.n\n\n"


class SyntheticPairTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory(prefix="poseidon-synthetic-monitor-check-")
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name).resolve()
        self.packages = self.root / "packages"
        self.toolchain = self.packages / checker.TOOLCHAIN
        (self.toolchain / "bin").mkdir(parents=True)
        (self.toolchain / "package.json").write_text(json.dumps({"name": checker.TOOLCHAIN, "version": checker.TOOLCHAIN_VERSION}))
        for name in ("nm", "objdump"):
            (self.toolchain / "bin" / f"xtensa-esp32-elf-{name}").write_bytes(b"SYNTHETIC NOT EXECUTABLE; vendor output is mocked")
        self.builds = {}
        self.logs = {}
        for profile in ("monitor_disabled", "monitor_persisted"):
            build = self.root / (profile + "-build")
            (build / profile).mkdir(parents=True)
            (build / profile / "firmware.elf").write_bytes(synthetic_elf())
            (build / profile / "firmware.bin").write_bytes(b"SYNTHETIC BIN " + profile.encode())
            (build / f"sdkconfig.{profile}").write_text("# SYNTHETIC SDKCONFIG, not generated by a build\n")
            self.builds[profile] = build
            self.logs[profile] = self.root / (profile + ".log")
            self.logs[profile].write_text(self.log_text(profile))
        self.nm_output = synthetic_nm()
        self.objdump_transform = lambda text: text
        self.disassembly_transform = lambda text, symbol: text
        self.tool_calls = []
        self.mock_tool = patch.object(checker, "run_tool", side_effect=self.fake_tool).start()
        self.addCleanup(patch.stopall)

    def command(self, profile: str) -> str:
        return f"xtensa-esp32-elf-g++ -o {self.builds[profile] / profile / 'src/main.cpp.o'} -c -std=gnu++17 -Og -Wall -fdata-sections -DPLATFORMIO=60118 -D{checker.MACRO}={int(profile == 'monitor_persisted')} -Isynthetic/include src/main.cpp"

    def log_text(self, profile: str) -> str:
        return f"SYNTHETIC VERBOSE BUILD LOG; no compiler was run\n{self.command(profile)}\n========================= [SUCCESS] Took 1.23 seconds =========================\n{profile} SUCCESS 00:00:01.234\n"

    def fake_tool(self, argv: list[str]) -> str:
        self.tool_calls.append(argv)
        if argv[1] == "-f":
            return self.objdump_transform(synthetic_objdump(Path(argv[2])))
        if argv[1] == "-d":
            self.assertEqual(len(argv), 4)
            self.assertTrue(argv[2].startswith("--disassemble="))
            symbol = argv[2].split("=", 1)[1]
            self.assertIn(symbol, checker.MANUAL_DISASSEMBLY_SYMBOLS.values())
            return self.disassembly_transform(synthetic_disassembly(Path(argv[3]), symbol), symbol)
        self.assertEqual(argv[1], "-C")
        return self.nm_output

    def pair(self) -> dict:
        return checker.check_pair(self.builds["monitor_disabled"], self.builds["monitor_persisted"], self.logs["monitor_disabled"], self.logs["monitor_persisted"], self.packages)

    def replace_log(self, old: str, new: str, profile: str = "monitor_disabled") -> None:
        log = self.logs[profile]
        log.write_text(log.read_text().replace(old, new))

    def artifact(self, name: str, profile: str = "monitor_disabled") -> Path:
        if name == "sdkconfig":
            return self.builds[profile] / f"sdkconfig.{profile}"
        return self.builds[profile] / profile / f"firmware.{name}"

    def test_synthetic_pair_accepts_flags_and_symbols_without_semantic_or_field_claim(self) -> None:
        report = self.pair()
        self.assertTrue(report["passed"])
        self.assertTrue(report["monitor_binaries_distinct"])
        self.assertFalse(report["release_authorized"])
        self.assertFalse(report["initializer_semantics_verified"])
        self.assertTrue(report["manual_initializer_review_required"])
        self.assertFalse(report["fresh_build_provenance_verified"])
        self.assertFalse(report["warning_free_claim"])
        self.assertEqual(len(report["profiles"]), 2)
        self.assertEqual(report["diagnostics_count"], 0)
        for profile in report["profiles"]:
            self.assertEqual(set(profile["defined_text_symbols"]), set(checker.REQUIRED_TEXT_SYMBOLS))
            self.assertEqual(len(profile["artifacts"]["bin"]["sha256"]), 64)
            self.assertFalse(profile["log"]["compile_commands_used"])
        self.assertEqual(len(self.tool_calls), 8)
        self.assertTrue(all(Path(call[0]).parent == self.toolchain / "bin" for call in self.tool_calls))

    def test_raw_manual_disassembly_is_retained_with_command_output_and_elf_hashes(self) -> None:
        report = self.pair()
        for profile in report["profiles"]:
            elf = Path(profile["artifacts"]["elf"]["path"])
            evidence = profile["manual_disassembly"]
            self.assertEqual(set(evidence), {"initializer", "app_main"})
            for name, symbol in checker.MANUAL_DISASSEMBLY_SYMBOLS.items():
                item = evidence[name]
                command = [str(self.toolchain / "bin/xtensa-esp32-elf-objdump"), "-d", f"--disassemble={symbol}", str(elf)]
                raw = synthetic_disassembly(elf, symbol)
                self.assertEqual(item["output"], raw)
                self.assertEqual(item["output_bytes"], len(raw.encode("utf-8")))
                self.assertEqual(item["output_sha256"], hashlib.sha256(raw.encode("utf-8")).hexdigest())
                self.assertEqual(item["command"], command)
                command_json = json.dumps(command, ensure_ascii=True, separators=(",", ":"))
                self.assertEqual(item["command_sha256"], hashlib.sha256(command_json.encode("utf-8")).hexdigest())
                self.assertEqual(item["elf_sha256"], profile["artifacts"]["elf"]["sha256"])
                self.assertFalse(item["semantics_verified"])
        self.assertFalse(report["initializer_semantics_verified"])
        self.assertTrue(report["manual_initializer_review_required"])

    def test_manual_disassembly_empty_and_size_limits_fail(self) -> None:
        for replacement in ("", "SYNTHETIC" * (checker.MAX_DISASSEMBLY_BYTES // 9 + 1)):
            with self.subTest(bytes=len(replacement)):
                self.disassembly_transform = lambda _text, _symbol: replacement
                with self.assertRaisesRegex(checker.CheckError, "disassembly.*size limit"):
                    self.pair()
        self.disassembly_transform = lambda text, _symbol: text
        with patch.object(checker, "MAX_DISASSEMBLY_BYTES", 16), self.assertRaisesRegex(checker.CheckError, "size limit"):
            self.pair()

    def test_missing_wrong_and_duplicate_manual_disassembly_frames_fail(self) -> None:
        for target in checker.MANUAL_DISASSEMBLY_SYMBOLS.values():
            for mutation in (lambda text: text.replace(f"<{target}>", "<synthetic_other_symbol>"), lambda text: text.replace("firmware.elf:", "wrong.elf:"), lambda text: text.replace("elf32-xtensa-le", "elf64-x86-64"), lambda text: text + f"400d2000 <{target}>:\n"):
                with self.subTest(target=target, mutation=mutation):
                    self.disassembly_transform = lambda text, symbol: mutation(text) if symbol == target else text
                    with self.assertRaisesRegex(checker.CheckError, "manual disassembly frame"):
                        self.pair()

    def test_elf_changed_during_manual_disassembly_is_rechecked_and_rejected(self) -> None:
        def mutate_during_disassembly(argv: list[str]) -> str:
            if argv[1] == "-d":
                path = self.artifact("elf")
                data = path.read_bytes()
                path.write_bytes(data[:200] + b"X" + data[201:])
            return self.fake_tool(argv)
        self.mock_tool.side_effect = mutate_during_disassembly
        with self.assertRaisesRegex(checker.CheckError, "artifact changed"):
            self.pair()
        self.assertTrue(any(argv[1] == "-d" for argv in self.tool_calls))

    def test_manual_disassembly_tool_failure_cannot_produce_passing_report(self) -> None:
        def fail_disassembly(argv: list[str]) -> str:
            if argv[1] == "-d":
                raise checker.CheckError("synthetic manual disassembly timeout")
            return self.fake_tool(argv)
        self.mock_tool.side_effect = fail_disassembly
        with self.assertRaisesRegex(checker.CheckError, "disassembly timeout"):
            self.pair()

    def test_synthetic_git_metadata_and_cmake_warning_are_preserved_nonfatal(self) -> None:
        diagnostics = "-- git rev-parse returned 'fatal: not a git repository'\nfatal: not a git repository: (null)\n-- Could not use 'git describe' to determine PROJECT_VER.\nCMake Warning:\n  Manually-specified variables were not used by the project:\n\n    LEGACY_INCLUDE_COMMON_HEADERS\n\n"
        self.replace_log("SYNTHETIC VERBOSE", diagnostics + "SYNTHETIC VERBOSE")
        report = self.pair()
        self.assertEqual(report["diagnostics_count"], 5)
        records = report["profiles"][0]["log"]["diagnostics"]
        self.assertIn("LEGACY_INCLUDE_COMMON_HEADERS", records[3]["text"])
        self.assertIn("fatal: not a git repository", records[1]["text"])
        self.assertFalse(report["warning_free_claim"])

    def test_diagnostics_count_is_not_silently_limited_to_retained_records(self) -> None:
        self.replace_log("SYNTHETIC VERBOSE", "synthetic.cpp: warning: synthetic fixture\n" * 105 + "SYNTHETIC VERBOSE")
        result = self.pair()["profiles"][0]["log"]
        self.assertEqual(result["diagnostics_count"], 105)
        self.assertEqual(len(result["diagnostics"]), 100)
        self.assertTrue(result["diagnostics_truncated"])

    def test_missing_monitor_flag_fails(self) -> None:
        self.replace_log(f"-D{checker.MACRO}=0", "")
        with self.assertRaisesRegex(checker.CheckError, "gate flag"):
            self.pair()

    def test_wrong_monitor_flags_fail_for_each_profile(self) -> None:
        for profile, wrong in (("monitor_disabled", 1), ("monitor_persisted", 0)):
            with self.subTest(profile=profile):
                self.logs[profile].write_text(self.log_text(profile).replace(f"-D{checker.MACRO}={1-wrong}", f"-D{checker.MACRO}={wrong}"))
                with self.assertRaisesRegex(checker.CheckError, "gate flag"):
                    self.pair()
                self.logs[profile].write_text(self.log_text(profile))

    def test_contradictory_duplicate_unset_and_missing_value_flags_fail(self) -> None:
        original = f"-D{checker.MACRO}=0"
        for replacement in (f"{original} -D{checker.MACRO}=1", f"{original} {original}", f"{original} -U{checker.MACRO}", f"-D{checker.MACRO}", f"-D{checker.MACRO}=", f"-D{checker.MACRO}=2", f"-D{checker.MACRO}=00", f"-D{checker.MACRO}=false", f"-D {checker.MACRO}=0", f"-U {checker.MACRO}"):
            with self.subTest(replacement=replacement):
                self.logs["monitor_disabled"].write_text(self.log_text("monitor_disabled").replace(original, replacement))
                with self.assertRaisesRegex(checker.CheckError, "gate flag"):
                    self.pair()

    def test_flags_in_banner_or_another_source_do_not_replace_app_main_flag(self) -> None:
        self.replace_log(f"-D{checker.MACRO}=0", "")
        self.replace_log("SYNTHETIC VERBOSE", f"build_flags = -D{checker.MACRO}=0\nxtensa-esp32-elf-g++ -c other.cpp -D{checker.MACRO}=0\nSYNTHETIC VERBOSE")
        with self.assertRaisesRegex(checker.CheckError, "gate flag"):
            self.pair()

    def test_compile_commands_metadata_is_never_read_or_accepted(self) -> None:
        path = self.builds["monitor_disabled"] / "monitor_disabled/compile_commands.json"
        path.write_text(json.dumps([{"command": self.command("monitor_disabled"), "file": str(checker.APP_SOURCE)}]))
        self.replace_log(self.command("monitor_disabled"), "Compiling synthetic/main.cpp.o")
        with self.assertRaisesRegex(checker.CheckError, "exactly one verbose"):
            self.pair()
        self.logs["monitor_disabled"].write_text(path.read_text())
        with self.assertRaises(checker.CheckError):
            self.pair()

    def test_duplicate_compile_record_fails_even_when_flag_matches(self) -> None:
        command = self.command("monitor_disabled")
        self.replace_log(command, command + "\n" + command)
        with self.assertRaisesRegex(checker.CheckError, "exactly one verbose"):
            self.pair()

    def test_nonverbose_log_with_only_success_fails(self) -> None:
        self.replace_log(self.command("monitor_disabled"), "Compiling build/monitor_disabled/src/main.cpp.o")
        with self.assertRaisesRegex(checker.CheckError, "exactly one verbose"):
            self.pair()

    def test_missing_and_failed_success_summaries_fail(self) -> None:
        for old, replacement in (("[SUCCESS]", "[FAILED]"), ("[SUCCESS]", "SUCCESS"), ("monitor_disabled SUCCESS", "monitor_disabled IGNORED"), ("monitor_disabled SUCCESS", "different_profile SUCCESS")):
            with self.subTest(replacement=replacement):
                self.logs["monitor_disabled"].write_text(self.log_text("monitor_disabled").replace(old, replacement))
                with self.assertRaises(checker.CheckError):
                    self.pair()

    def test_compile_error_and_cmake_error_fail_despite_success_summary(self) -> None:
        for diagnostic in ("main.cpp: error: synthetic failure", "fatal error: synthetic failure", "CMake Error at synthetic.cmake:1"):
            with self.subTest(diagnostic=diagnostic):
                self.logs["monitor_disabled"].write_text(diagnostic + "\n" + self.log_text("monitor_disabled"))
                with self.assertRaisesRegex(checker.CheckError, "failure diagnostic"):
                    self.pair()

    def test_unknown_fatal_diagnostic_is_not_treated_as_git_metadata(self) -> None:
        self.replace_log("SYNTHETIC VERBOSE", "fatal: synthetic compiler termination\nSYNTHETIC VERBOSE")
        with self.assertRaisesRegex(checker.CheckError, "failure diagnostic"):
            self.pair()

    def test_wrong_source_and_build_object_fail(self) -> None:
        for old, replacement in ((" src/main.cpp", " /unrelated/main.cpp"), (" src/main.cpp", " src/not_app.cpp"), ("/src/main.cpp.o", "/src/wrong.cpp.o"), ("/monitor_disabled/src/main.cpp.o", "/monitor_persisted/src/main.cpp.o")):
            with self.subTest(replacement=replacement):
                self.logs["monitor_disabled"].write_text(self.log_text("monitor_disabled").replace(old, replacement))
                with self.assertRaises(checker.CheckError):
                    self.pair()

    def test_absolute_target_source_and_pinned_compiler_are_accepted(self) -> None:
        self.replace_log(" src/main.cpp", f" {checker.APP_SOURCE}")
        self.replace_log("xtensa-esp32-elf-g++", str(self.toolchain / "bin/xtensa-esp32-elf-g++"))
        self.assertTrue(self.pair()["passed"])

    def test_other_compiler_path_and_wrapper_records_fail(self) -> None:
        for compiler in ("g++", "/untrusted/bin/xtensa-esp32-elf-g++", "ccache xtensa-esp32-elf-g++", "echo xtensa-esp32-elf-g++", "env FLAG=value xtensa-esp32-elf-g++"):
            with self.subTest(compiler=compiler):
                self.logs["monitor_disabled"].write_text(self.log_text("monitor_disabled").replace("xtensa-esp32-elf-g++", compiler))
                with self.assertRaises(checker.CheckError):
                    self.pair()

    def test_shell_response_file_and_preprocessor_indirection_records_fail(self) -> None:
        for option in ("@synthetic.rsp", "; echo fake", "&& true", "$(touch ignored)", "`false`", "-include synthetic.h", "-imacros synthetic.h", "-Wp,-DSYNTHETIC=1", "-Xpreprocessor -DSYNTHETIC=1", "--specs=synthetic", "-fplugin=synthetic", "-fpreprocessed", "-fdirectives-only", "-UOTHER"):
            with self.subTest(option=option):
                self.logs["monitor_disabled"].write_text(self.log_text("monitor_disabled").replace(" -Og", f" {option} -Og"))
                with self.assertRaises(checker.CheckError):
                    self.pair()
        self.mock_tool.assert_not_called()

    def test_malformed_quoting_and_control_records_fail(self) -> None:
        for content in (self.log_text("monitor_disabled").replace(" -Og", " ' -Og"), self.log_text("monitor_disabled") + "\x00", "\x1b[32m" + self.log_text("monitor_disabled")):
            with self.subTest(content=content[:30]):
                self.logs["monitor_disabled"].write_text(content)
                with self.assertRaises(checker.CheckError):
                    self.pair()

    def test_missing_each_required_symbol_fails_including_exact_app_main(self) -> None:
        for name in checker.REQUIRED_TEXT_SYMBOLS:
            with self.subTest(name=name):
                self.nm_output = "\n".join(line for line in synthetic_nm().splitlines() if not line.endswith(" " + name))
                with self.assertRaisesRegex(checker.CheckError, "missing required"):
                    self.pair()

    def test_undefined_weak_data_and_zero_address_required_symbols_fail(self) -> None:
        for replacement in ("         U app_main", "400d1000 W app_main", "3ffb1000 D app_main", "00000000 T app_main"):
            with self.subTest(replacement=replacement):
                self.nm_output = synthetic_nm().replace("400d1000 T app_main", replacement)
                with self.assertRaisesRegex(checker.CheckError, "not text"):
                    self.pair()

    def test_duplicate_required_symbol_fails(self) -> None:
        self.nm_output += "400d4000 T app_main\n"
        with self.assertRaisesRegex(checker.CheckError, "duplicate"):
            self.pair()

    def test_symbol_substrings_clones_and_overloads_do_not_count(self) -> None:
        for suffix in ("_synthetic", " [clone .isra.0]", "(int)"):
            with self.subTest(suffix=suffix):
                self.nm_output = synthetic_nm().replace(" T app_main\n", f" T app_main{suffix}\n")
                with self.assertRaisesRegex(checker.CheckError, "missing required"):
                    self.pair()

    def test_unsupported_nm_records_fail_even_after_required_symbols(self) -> None:
        for record in ("unsupported diagnostic", "400d0000 ? synthetic", "0 T short_address", "400d000000000000 T wide_address", "archive.a(object.o):", "app_main T 400d1000"):
            with self.subTest(record=record):
                self.nm_output = synthetic_nm() + record + "\n"
                with self.assertRaisesRegex(checker.CheckError, "unsupported nm"):
                    self.pair()

    def test_wrong_elf_class_endianness_machine_and_type_fail(self) -> None:
        for offset, value in ((4, 2), (5, 2), (6, 0), (16, 3), (18, 243), (20, 2)):
            with self.subTest(offset=offset):
                data = bytearray(synthetic_elf())
                data[offset] = value
                self.artifact("elf").write_bytes(data)
                with self.assertRaises(checker.CheckError):
                    self.pair()
        self.mock_tool.assert_not_called()

    def test_truncated_or_out_of_bounds_elf_tables_fail(self) -> None:
        for data in (synthetic_elf()[:40], synthetic_elf()[:100], synthetic_elf()[:32] + b"\xff\xff\xff\xff" + synthetic_elf()[36:]):
            with self.subTest(length=len(data)):
                self.artifact("elf").write_bytes(data)
                with self.assertRaises(checker.CheckError):
                    self.pair()

    def test_wrong_objdump_format_architecture_flags_entry_and_extra_records_fail(self) -> None:
        for old, new in (("elf32-xtensa-le", "elf64-x86-64"), ("architecture: xtensa", "architecture: riscv"), ("0x00000112", "0x00000000"), ("EXEC_P, HAS_SYMS, D_PAGED", "HAS_SYMS"), ("0x40081200", "0x40081300"), ("start address", "synthetic extra record\nstart address"), ("firmware.elf:", "other.elf:")):
            with self.subTest(new=new):
                self.objdump_transform = lambda text, old=old, new=new: text.replace(old, new)
                with self.assertRaises(checker.CheckError):
                    self.pair()

    def test_identical_monitor_binaries_fail(self) -> None:
        self.artifact("bin", "monitor_persisted").write_bytes(self.artifact("bin").read_bytes())
        with self.assertRaisesRegex(checker.CheckError, "identical"):
            self.pair()

    def test_missing_artifacts_fail_for_all_required_kinds(self) -> None:
        for name in ("elf", "bin", "sdkconfig"):
            with self.subTest(name=name):
                path = self.artifact(name)
                data = path.read_bytes()
                path.unlink()
                with self.assertRaises(OSError):
                    self.pair()
                path.write_bytes(data)

    def test_empty_artifacts_fail_for_all_required_kinds(self) -> None:
        for name in ("elf", "bin", "sdkconfig"):
            with self.subTest(name=name):
                path = self.artifact(name)
                data = path.read_bytes()
                path.write_bytes(b"")
                with self.assertRaisesRegex(checker.CheckError, "empty"):
                    self.pair()
                path.write_bytes(data)

    def test_symlink_artifacts_fail_without_touching_targets(self) -> None:
        for name in ("elf", "bin", "sdkconfig"):
            with self.subTest(name=name):
                path = self.artifact(name)
                target = self.root / ("synthetic-target-" + name)
                data = path.read_bytes()
                path.rename(target)
                path.symlink_to(target)
                with self.assertRaisesRegex(checker.CheckError, "non-symlink"):
                    self.pair()
                self.assertEqual(target.read_bytes(), data)
                path.unlink()
                target.rename(path)

    def test_directory_and_fifo_artifacts_fail_before_reading(self) -> None:
        path = self.artifact("bin")
        path.unlink()
        path.mkdir()
        with self.assertRaisesRegex(checker.CheckError, "regular"):
            self.pair()
        path.rmdir()
        os.mkfifo(path)
        with self.assertRaisesRegex(checker.CheckError, "regular"):
            self.pair()

    def test_oversized_artifacts_fail_before_vendor_inspection(self) -> None:
        for limit in ("MAX_ELF_BYTES", "MAX_BIN_BYTES", "MAX_CONFIG_BYTES"):
            with self.subTest(limit=limit), patch.object(checker, limit, 4):
                with self.assertRaisesRegex(checker.CheckError, "size limit"):
                    self.pair()
        self.mock_tool.assert_not_called()

    def test_symlink_build_and_profile_directories_fail(self) -> None:
        for path in (self.builds["monitor_disabled"] / "monitor_disabled", self.builds["monitor_disabled"]):
            with self.subTest(path=path):
                target = self.root / "synthetic-relocated"
                path.rename(target)
                path.symlink_to(target, target_is_directory=True)
                with self.assertRaisesRegex(checker.CheckError, "non-symlink directory"):
                    self.pair()
                path.unlink()
                target.rename(path)

    def test_same_and_nested_build_roots_fail(self) -> None:
        original = self.builds["monitor_persisted"]
        for path in (self.builds["monitor_disabled"], self.builds["monitor_disabled"] / "monitor_disabled"):
            with self.subTest(path=path):
                self.builds["monitor_persisted"] = path
                with self.assertRaisesRegex(checker.CheckError, "distinct and non-nested"):
                    self.pair()
        self.builds["monitor_persisted"] = original

    def test_shared_hardlinked_sdkconfig_fails(self) -> None:
        self.artifact("sdkconfig", "monitor_persisted").unlink()
        os.link(self.artifact("sdkconfig"), self.artifact("sdkconfig", "monitor_persisted"))
        with self.assertRaisesRegex(checker.CheckError, "share one sdkconfig"):
            self.pair()

    def test_missing_empty_symlink_and_oversized_logs_fail(self) -> None:
        path = self.logs["monitor_disabled"]
        data = path.read_bytes()
        path.unlink()
        with self.assertRaises(OSError):
            self.pair()
        path.write_bytes(b"")
        with self.assertRaisesRegex(checker.CheckError, "empty"):
            self.pair()
        path.unlink()
        target = self.root / "synthetic-log-target"
        target.write_bytes(data)
        path.symlink_to(target)
        with self.assertRaisesRegex(checker.CheckError, "non-symlink"):
            self.pair()
        path.unlink()
        path.write_bytes(data)
        with patch.object(checker, "MAX_LOG_BYTES", 16), self.assertRaisesRegex(checker.CheckError, "size limit"):
            self.pair()

    def test_non_utf8_and_oversized_log_records_fail(self) -> None:
        path = self.logs["monitor_disabled"]
        path.write_bytes(b"\xff" + self.log_text("monitor_disabled").encode())
        with self.assertRaisesRegex(checker.CheckError, "UTF-8"):
            self.pair()
        path.write_text(self.log_text("monitor_disabled"))
        with patch.object(checker, "MAX_LINE_BYTES", 64), self.assertRaisesRegex(checker.CheckError, "line size"):
            self.pair()

    def test_missing_wrong_and_malformed_toolchain_manifest_fail(self) -> None:
        path = self.toolchain / "package.json"
        for data in ("{}", "[]", "{", json.dumps({"name": checker.TOOLCHAIN, "version": "not-pinned"})):
            with self.subTest(data=data):
                path.write_text(data)
                with self.assertRaises((checker.CheckError, json.JSONDecodeError)):
                    self.pair()
        path.unlink()
        with self.assertRaises(OSError):
            self.pair()
        self.mock_tool.assert_not_called()

    def test_duplicate_toolchain_name_and_version_fields_fail_in_either_order(self) -> None:
        path = self.toolchain / "package.json"
        correct = {"name": checker.TOOLCHAIN, "version": checker.TOOLCHAIN_VERSION}
        for key in ("name", "version"):
            for first, second in (("wrong", correct[key]), (correct[key], "wrong"), (correct[key], correct[key])):
                with self.subTest(key=key, first=first, second=second):
                    other = "version" if key == "name" else "name"
                    path.write_text("{" + f'{json.dumps(key)}:{json.dumps(first)},{json.dumps(key)}:{json.dumps(second)},{json.dumps(other)}:{json.dumps(correct[other])}' + "}")
                    with self.assertRaisesRegex(checker.CheckError, "duplicate"):
                        self.pair()
        self.mock_tool.assert_not_called()

    def test_nonfinite_manifest_numbers_fail_including_exponent_overflow(self) -> None:
        path = self.toolchain / "package.json"
        prefix = json.dumps({"name": checker.TOOLCHAIN, "version": checker.TOOLCHAIN_VERSION})[:-1]
        for value in ("NaN", "Infinity", "-Infinity", "1e9999", "-1e9999", "[NaN]", '{"nested":Infinity}'):
            with self.subTest(value=value):
                path.write_text(prefix + ',"synthetic":' + value + "}")
                with self.assertRaisesRegex(checker.CheckError, "nonfinite"):
                    self.pair()
        self.mock_tool.assert_not_called()

    def test_nested_duplicate_manifest_fields_fail(self) -> None:
        path = self.toolchain / "package.json"
        prefix = json.dumps({"name": checker.TOOLCHAIN, "version": checker.TOOLCHAIN_VERSION})[:-1]
        path.write_text(prefix + ',"synthetic":{"x":1,"x":2}}')
        with self.assertRaisesRegex(checker.CheckError, "duplicate"):
            self.pair()
        self.mock_tool.assert_not_called()

    def test_finite_manifest_metadata_remains_accepted(self) -> None:
        path = self.toolchain / "package.json"
        path.write_text(json.dumps({"name": checker.TOOLCHAIN, "version": checker.TOOLCHAIN_VERSION, "synthetic": {"finite": 1.5}}))
        self.assertTrue(self.pair()["passed"])

    def test_missing_empty_and_symlink_vendor_tools_fail(self) -> None:
        path = self.toolchain / "bin/xtensa-esp32-elf-nm"
        path.unlink()
        with self.assertRaises(OSError):
            self.pair()
        path.write_bytes(b"")
        with self.assertRaisesRegex(checker.CheckError, "empty"):
            self.pair()
        path.unlink()
        path.symlink_to(self.toolchain / "bin/xtensa-esp32-elf-objdump")
        with self.assertRaisesRegex(checker.CheckError, "non-symlink"):
            self.pair()

    def test_changed_artifact_during_inspection_fails(self) -> None:
        def mutate(argv: list[str]) -> str:
            self.artifact("bin").write_bytes(b"SYNTHETIC changed while tools run")
            return self.fake_tool(argv)
        self.mock_tool.side_effect = mutate
        with self.assertRaisesRegex(checker.CheckError, "artifact changed|size limit|file changed"):
            self.pair()

    def test_vendor_failures_propagate_and_never_produce_passing_report(self) -> None:
        self.mock_tool.side_effect = checker.CheckError("synthetic vendor timeout")
        with self.assertRaisesRegex(checker.CheckError, "vendor timeout"):
            self.pair()

    def test_cli_emits_json_for_synthetic_success_and_failure(self) -> None:
        argv = ["--disabled-build", str(self.builds["monitor_disabled"]), "--persisted-build", str(self.builds["monitor_persisted"]), "--disabled-log", str(self.logs["monitor_disabled"]), "--persisted-log", str(self.logs["monitor_persisted"]), "--packages", str(self.packages)]
        output = io.StringIO()
        with redirect_stdout(output):
            self.assertEqual(checker.main(argv), 0)
        self.assertFalse(json.loads(output.getvalue())["release_authorized"])
        self.artifact("bin").unlink()
        output = io.StringIO()
        with redirect_stdout(output):
            self.assertEqual(checker.main(argv), 1)
        result = json.loads(output.getvalue())
        self.assertFalse(result["passed"])
        self.assertFalse(result["release_authorized"])
        self.assertIn("error", result)


class SyntheticToolProcessTests(unittest.TestCase):
    """Only Python snippets as synthetic vendor stand-ins; never native tools."""

    def test_fixture_stdout_and_stderr_are_both_captured(self) -> None:
        result = checker.run_tool([sys.executable, "-c", "import sys; print('synthetic stdout'); print('synthetic stderr', file=sys.stderr)"])
        self.assertIn("synthetic stdout", result)
        self.assertIn("synthetic stderr", result)

    def test_fixture_nonzero_exit_is_rejected_with_diagnostic(self) -> None:
        with self.assertRaisesRegex(checker.CheckError, "exited 7.*synthetic failure"):
            checker.run_tool([sys.executable, "-c", "import sys; print('synthetic failure'); sys.exit(7)"])

    def test_fixture_timeout_is_bounded_and_reaped(self) -> None:
        started = time.monotonic()
        with patch.object(checker, "TOOL_TIMEOUT", 0.15), self.assertRaisesRegex(checker.CheckError, "timeout"):
            checker.run_tool([sys.executable, "-c", "import time; time.sleep(60)"])
        self.assertLess(time.monotonic() - started, 5)

    def test_fixture_closed_output_then_hang_still_times_out(self) -> None:
        with patch.object(checker, "TOOL_TIMEOUT", 0.15), self.assertRaisesRegex(checker.CheckError, "timeout"):
            checker.run_tool([sys.executable, "-c", "import os,time; os.close(1); os.close(2); time.sleep(60)"])

    def test_fixture_output_limit_is_bounded(self) -> None:
        with patch.object(checker, "MAX_TOOL_OUTPUT", 128), self.assertRaisesRegex(checker.CheckError, "output exceeds"):
            checker.run_tool([sys.executable, "-c", "print('SYNTHETIC' * 10000)"])

    def test_fixture_invalid_output_encoding_fails(self) -> None:
        with self.assertRaisesRegex(checker.CheckError, "UTF-8"):
            checker.run_tool([sys.executable, "-c", "import os; os.write(1, bytes([255]))"])

    def test_fixture_receives_eof_stdin_and_no_shell_interpretation(self) -> None:
        result = checker.run_tool([sys.executable, "-c", "import sys; print(repr(sys.stdin.read())); print(sys.argv[1])", "$(synthetic-not-a-command)"])
        self.assertIn("''", result)
        self.assertIn("$(synthetic-not-a-command)", result)


class PriorHandlerRaised(RuntimeError):
    """Safe sentinel: a broken cancellation regression must not kill unittest."""


class SyntheticCancellationTests(unittest.TestCase):
    """Real OS signals and mocked delivery, with independently owned cleanup."""

    def setUp(self) -> None:
        self.previous = {sig: signal.getsignal(sig) for sig in checker.INSPECTION_SIGNALS}
        self.previous_mask = signal.pthread_sigmask(signal.SIG_BLOCK, set())
        self.real_popen = subprocess.Popen
        self.real_killpg = os.killpg
        self.real_signal = signal.signal
        self.spawned = []
        self.on_spawn = None
        self.prior_deliveries = []

        def prior_handler(signum: int, _frame: object) -> None:
            self.prior_deliveries.append(signum)
            raise PriorHandlerRaised(f"previous handler received {signum}")

        self.prior_handler = prior_handler
        self.addCleanup(self.cleanup_owned)
        for sig in checker.INSPECTION_SIGNALS:
            signal.signal(sig, self.prior_handler)
        self.spawn_patch = patch.object(checker.subprocess, "Popen", side_effect=self.capture_spawn)
        self.spawn_patch.start()
        self.addCleanup(self.spawn_patch.stop)

    def capture_spawn(self, *args, **kwargs):
        process = self.real_popen(*args, **kwargs)
        # Test ownership is recorded BEFORE injecting the production spawn gap.
        # Even a broken checker cannot leave our Python fixture running.
        self.spawned.append(process)
        if self.on_spawn is not None:
            self.on_spawn(process)
        return process

    def cleanup_owned(self) -> None:
        signal.pthread_sigmask(signal.SIG_BLOCK, checker.INSPECTION_SIGNALS)
        try:
            for process in self.spawned:
                try:
                    self.real_killpg(process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                finally:
                    if process.stdout is not None:
                        process.stdout.close()
                    process.wait(timeout=5)
        finally:
            for sig, handler in self.previous.items():
                self.real_signal(sig, handler)
            signal.pthread_sigmask(signal.SIG_SETMASK, self.previous_mask)

    def assert_restored_and_reaped(self) -> None:
        self.assertEqual(signal.pthread_sigmask(signal.SIG_BLOCK, set()), self.previous_mask)
        for sig in checker.INSPECTION_SIGNALS:
            self.assertIs(signal.getsignal(sig), self.prior_handler)
        for process in self.spawned:
            self.assertIsNotNone(process.returncode)
            with self.assertRaises(ProcessLookupError):
                self.real_killpg(process.pid, 0)

    @staticmethod
    def deliver(signum: int, actual: bool) -> None:
        if actual:
            os.kill(os.getpid(), signum)
        else:
            signal.getsignal(signum)(signum, None)

    @staticmethod
    def sleeping_fixture() -> list[str]:
        return [sys.executable, "-c", "import time; time.sleep(60)"]

    def active_cancellation(self, actual: bool) -> None:
        for signum in checker.INSPECTION_SIGNALS:
            with self.subTest(signum=signum):
                def deliver(_timeout: float) -> list:
                    self.deliver(signum, actual)
                    return []
                with patch.object(checker.selectors.DefaultSelector, "select", side_effect=deliver):
                    with self.assertRaises(checker.InspectionInterrupted) as caught:
                        checker.run_tool(self.sleeping_fixture())
                self.assertEqual(caught.exception.signum, signum)
                self.assert_restored_and_reaped()
        self.assertEqual(self.prior_deliveries, [])

    def test_actual_sigint_and_sigterm_during_inspection_reap_group(self) -> None:
        self.active_cancellation(actual=True)

    def test_mocked_sigint_and_sigterm_during_inspection_reap_group(self) -> None:
        self.active_cancellation(actual=False)

    def spawn_gap_cancellation(self, actual: bool) -> None:
        for signum in checker.INSPECTION_SIGNALS:
            with self.subTest(signum=signum):
                self.on_spawn = lambda _process: self.deliver(signum, actual)
                with self.assertRaises(checker.InspectionInterrupted) as caught:
                    checker.run_tool(self.sleeping_fixture())
                self.assertEqual(caught.exception.signum, signum)
                self.assert_restored_and_reaped()
        self.assertEqual(self.prior_deliveries, [])

    def test_actual_sigint_and_sigterm_in_spawn_registration_gap_are_deferred(self) -> None:
        self.spawn_gap_cancellation(actual=True)

    def test_mocked_sigint_and_sigterm_in_spawn_registration_gap_are_deferred(self) -> None:
        self.spawn_gap_cancellation(actual=False)

    def test_first_cancellation_is_preserved_when_both_signals_arrive_in_spawn_gap(self) -> None:
        def interrupt_twice(_process) -> None:
            self.deliver(signal.SIGTERM, actual=True)
            self.deliver(signal.SIGINT, actual=True)
        self.on_spawn = interrupt_twice
        with self.assertRaises(checker.InspectionInterrupted) as caught:
            checker.run_tool(self.sleeping_fixture())
        self.assertEqual(caught.exception.signum, signal.SIGTERM)
        self.assert_restored_and_reaped()

    def test_cancellation_during_protected_cleanup_is_reported_after_reaping(self) -> None:
        for signum in checker.INSPECTION_SIGNALS:
            with self.subTest(signum=signum):
                def kill_then_interrupt(pid: int, sig: int) -> None:
                    try:
                        self.real_killpg(pid, sig)
                    finally:
                        mask = signal.pthread_sigmask(signal.SIG_BLOCK, set())
                        self.assertTrue(set(checker.INSPECTION_SIGNALS) <= mask)
                        self.deliver(signum, actual=True)
                with patch.object(checker.os, "killpg", side_effect=kill_then_interrupt):
                    with self.assertRaises(checker.InspectionInterrupted) as caught:
                        checker.run_tool([sys.executable, "-c", "print('synthetic cleanup fixture')"])
                self.assertEqual(caught.exception.signum, signum)
                self.assert_restored_and_reaped()
        self.assertEqual(self.prior_deliveries, [])

    def test_signal_at_cleanup_entry_before_masking_cannot_abort_reaping(self) -> None:
        real_mask = signal.pthread_sigmask
        for signum in checker.INSPECTION_SIGNALS:
            with self.subTest(signum=signum):
                delivered = False

                def interrupt_before_mask(how, signals):
                    nonlocal delivered
                    if how == signal.SIG_BLOCK and set(signals) == set(checker.INSPECTION_SIGNALS) and not delivered:
                        delivered = True
                        self.deliver(signum, actual=True)
                    return real_mask(how, signals)

                with patch.object(checker.signal, "pthread_sigmask", side_effect=interrupt_before_mask):
                    with self.assertRaises(checker.InspectionInterrupted) as caught:
                        checker.run_tool([sys.executable, "-c", "print('synthetic cleanup transition')"])
                self.assertTrue(delivered)
                self.assertEqual(caught.exception.signum, signum)
                self.assert_restored_and_reaped()

    def test_actual_cancellation_after_output_closes_does_not_wait_for_tool_timeout(self) -> None:
        for signum in checker.INSPECTION_SIGNALS:
            with self.subTest(signum=signum):
                def arm_wait(process) -> None:
                    real_wait = process.wait
                    delivered = False

                    def wait(*args, **kwargs):
                        nonlocal delivered
                        if not delivered:
                            delivered = True
                            self.deliver(signum, actual=True)
                        return real_wait(*args, **kwargs)
                    process.wait = wait

                self.on_spawn = arm_wait
                started = time.monotonic()
                with self.assertRaises(checker.InspectionInterrupted) as caught:
                    checker.run_tool([sys.executable, "-c", "import os,time; os.close(1); os.close(2); time.sleep(60)"])
                self.assertEqual(caught.exception.signum, signum)
                self.assertLess(time.monotonic() - started, 2)
                self.assert_restored_and_reaped()

    def test_handler_restoration_finishes_before_a_restored_handler_can_raise(self) -> None:
        delivered = False

        def restore_then_interrupt(signum: int, handler):
            nonlocal delivered
            result = self.real_signal(signum, handler)
            if handler is self.prior_handler and not delivered:
                delivered = True
                self.assertTrue(set(checker.INSPECTION_SIGNALS) <= signal.pthread_sigmask(signal.SIG_BLOCK, set()))
                self.deliver(signal.SIGINT, actual=True)
            return result

        with patch.object(checker.signal, "signal", side_effect=restore_then_interrupt):
            with self.assertRaises(PriorHandlerRaised):
                checker.run_tool([sys.executable, "-c", "print('synthetic restoration fixture')"])
        self.assertTrue(delivered)
        self.assertEqual(self.prior_deliveries, [signal.SIGINT])
        self.assert_restored_and_reaped()

    def test_vendor_fixture_does_not_inherit_checker_blocked_signals(self) -> None:
        result = checker.run_tool([sys.executable, "-c", "import signal; mask=signal.pthread_sigmask(signal.SIG_BLOCK, set()); print(int(bool(mask & {signal.SIGINT, signal.SIGTERM})))"])
        self.assertEqual(result.strip(), "0")
        self.assert_restored_and_reaped()

    def test_spawn_failure_restores_handlers_and_signal_mask(self) -> None:
        with patch.object(checker.subprocess, "Popen", side_effect=OSError("synthetic spawn failure")):
            with self.assertRaisesRegex(OSError, "spawn failure"):
                checker.run_tool(self.sleeping_fixture())
        self.assertEqual(self.spawned, [])
        self.assert_restored_and_reaped()

    def test_signal_during_failed_spawn_is_reported_without_losing_handlers(self) -> None:
        for signum in checker.INSPECTION_SIGNALS:
            with self.subTest(signum=signum):
                def fail_spawn(*_args, **_kwargs):
                    self.deliver(signum, actual=False)
                    raise OSError("synthetic failure without a child")
                with patch.object(checker.subprocess, "Popen", side_effect=fail_spawn):
                    with self.assertRaises(checker.InspectionInterrupted) as caught:
                        checker.run_tool(self.sleeping_fixture())
                self.assertEqual(caught.exception.signum, signum)
                self.assert_restored_and_reaped()

    def test_timeout_and_output_cap_still_reap_and_restore(self) -> None:
        with patch.object(checker, "TOOL_TIMEOUT", 0.1):
            with self.assertRaisesRegex(checker.CheckError, "timeout"):
                checker.run_tool(self.sleeping_fixture())
        self.assert_restored_and_reaped()
        with patch.object(checker, "MAX_TOOL_OUTPUT", 16):
            with self.assertRaisesRegex(checker.CheckError, "output exceeds"):
                checker.run_tool([sys.executable, "-c", "print('SYNTHETIC' * 1000)"])
        self.assert_restored_and_reaped()

    def test_main_reports_actual_vendor_cancellation_as_nonrelease_json(self) -> None:
        argv = [item for name in ("disabled-build", "persisted-build", "disabled-log", "persisted-log", "packages") for item in ("--" + name, "/synthetic/not-read")]
        for signum in checker.INSPECTION_SIGNALS:
            with self.subTest(signum=signum):
                def deliver(_timeout: float) -> list:
                    self.deliver(signum, actual=True)
                    return []
                output = io.StringIO()
                with patch.object(checker, "check_pair", side_effect=lambda *_args: checker.run_tool(self.sleeping_fixture())):
                    with patch.object(checker.selectors.DefaultSelector, "select", side_effect=deliver), redirect_stdout(output):
                        self.assertEqual(checker.main(argv), 128 + signum)
                report = json.loads(output.getvalue())
                self.assertFalse(report["passed"])
                self.assertFalse(report["release_authorized"])
                self.assertEqual(report["interrupted_signal"], signum)
                self.assert_restored_and_reaped()
        self.assertEqual(self.prior_deliveries, [])

    def test_main_handles_sigint_and_sigterm_outside_vendor_call(self) -> None:
        argv = [item for name in ("disabled-build", "persisted-build", "disabled-log", "persisted-log", "packages") for item in ("--" + name, "/synthetic/not-read")]
        for signum in checker.INSPECTION_SIGNALS:
            with self.subTest(signum=signum):
                output = io.StringIO()
                with patch.object(checker, "check_pair", side_effect=lambda *_args: self.deliver(signum, actual=True)), redirect_stdout(output):
                    self.assertEqual(checker.main(argv), 128 + signum)
                self.assertEqual(json.loads(output.getvalue())["interrupted_signal"], signum)
                self.assert_restored_and_reaped()
        self.assertEqual(self.spawned, [])


if __name__ == "__main__":
    unittest.main()
